### ISSUE TITLE
Add Apache Tika to Deployment

### ISSUE THREAD

**Issue by rudolfjs** [rudolfjs/openwebui-deploy#3]
## Issue

Add the Apache Tika deployment to `docker-compose`.

Draft:

```yaml
  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    restart: unless-stopped
```

https://docs.openwebui.com/tutorials/integrations/apachetika/
